### PR TITLE
Incorrect option --repo instead of --repoid in manual

### PR DESCRIPTION
**Pull request by xenithorb**
Also added a line break to the synopsis to fix ambiguity

### CODE REVIEW

**Comment by ignatenkobrain** [comment]
LGTM!

**Comment by xenithorb** [comment]
As I investigate this further it's not simply a mis-documented switch, something else is awry:

https://github.com/xenithorb/dnf-plugins-core/blob/master/plugins/repoquery.py#L88-92

Here we see:

```
    parser.add_argument('--repo', metavar='REPO', action='append',
                        help=_('show only results from this REPO'))
    # make --repoid hidden compatibility alias for --repo
    parser.add_argument('--repoid', dest='repo', action='append',
                        help=argparse.SUPPRESS)
```

Of course the reason I'm here at all is simply because `--repo` does not work, the parent DNF command complains about it being bad format for `--repofrompath`, which is when `--repoid` works as intended.

Example: 

```
 #> dnf repoquery --repo fedora-nvidia 
usage: dnf [--allowerasing] [-b] [-C] [-c [config file]] [-d [debug level]]
           [--debugsolver] [--showduplicates] [-e ERRORLEVEL]
           [--rpmverbosity [debug level name]] [-q] [-v] [-y] [--assumeno]
           [--version] [--installroot [path]] [--enablerepo [repo]]
           [--disablerepo [repo]] [-x [package]] [--disableexcludes [repo]]
           [--repofrompath [repo,path]] [--noplugins] [--nogpgcheck]
           [--disableplugin [plugin]] [--color COLOR]
           [--releasever RELEASEVER] [--setopt SETOPTS] [--refresh] [-4] [-6]
           [--downloadonly] [-h]
Command line error: argument --repofrompath: bad format: fedora-nvidia
```

Further sleuthing shows this commit: https://github.com/xenithorb/dnf-plugins-core/commit/d1089a7ad58cab5daf9004ca41f9e58d9003806b

by @MichaelMraka which is basically the reverse of what I'm trying to accomplish. Perhaps "--repo" is no longer warranted due to the incompatibility with dnf proper, and we can just revert Michael's commit? 

I would not merge my PR at this point

**Comment by xenithorb** [comment]
I tried reverting the commit and pushing to this PR but it resulted in a few conflicts that I'm afraid I am not willing to attempt. This appears to be out of my capabilities at this point.

**Comment by mluscon** [comment]
Hi, we are currently working on a better argument parser which should also cover this case. Thank you for your attempt but I suppose it would be better to wait for a new parser than fix this bit separately. If you want to coordinate your work with us, you can find us on yum/freenode channel.

**Pull request closed without merging**
