### PR TITLE
Support remote files in dnf builddep

### PR DESCRIPTION
**Pull request by dmach**
Tests: https://github.com/rpm-software-management/ci-dnf-stack/pull/799

### CODE REVIEW

**Comment by dmach** [comment]
Tests: https://github.com/rpm-software-management/ci-dnf-stack/pull/799

**Comment by dmach** [comment]
Updated the commit message with the use case:

    The feature is primarily created for building containers for CI/CD tools.
    By providing a remote spec, it is possible to install build dependencies
    without cloning the whole git repository.

**Comment by Conan-Kudo** [comment]
@rh-atomic-bot r+

**Comment by dmach** [comment]
@rh-atomic-bot retry

**Pull request closed without merging**
