### PR TITLE
debuginfo-install: support cases where src.rpm name != binary package name

### PR DESCRIPTION
**Pull request by spacekpe**
This depends on my pull request #50.

Main behavioral change can be tested on krb5-libs package from Fedora 21. 
Dependency algorithm changes are visible e.g. on java-1.8.0-openjdk and java-1.8.0-openjdk-headless packages.

I hope it does not break something, I was not able to find any counter-example...

### CODE REVIEW

**Comment by rholy** [comment]
The (new) code seems to be OK. But I don't have time (now) to investigate how the plugin should really work, so I cannot confirm whether the change is OK and thus I cannot test it. Hopefully someone else can.

**Comment by spacekpe** [comment]
I have rebased the pull request on top of current master so it can be merged cleanly.

@rholy, what do you exactly mean with "I cannot confirm whether the change is OK and thus I cannot test it. Hopefully someone else can."?

Do you want to hear from someone else that it works for him? Or something else?

**Comment by rholy** [comment]
I simply don't know whether this is the expected behaviour. And I'm not the single person who can merge this.

**Comment by jsilhan** [comment]
@spacekpe , can you rebase it against origin/master, please. I know conflict is because posponing from our side but I don't want to mess it up doing myself. You know what you have changed better, thanks.

**Comment by spacekpe** [comment]
@jsilhan , rebased and re-tested locally. Thank you for merging this!

**Comment by jsilhan** [comment]
oh, I forgot to merge this. Done. Thanks.

**Pull request closed without merging**
