### PR TITLE
Add a argument to download and import GPG keys for repos

### PR DESCRIPTION
**Pull request by wheelerlaw**
Dependent on rpm-software-management/dnf#1865. 

Add an argument that tells DNF to download and import GPG keys for repos. 

Tests on the way. Looking for feedback on the implementation.

### CODE REVIEW

**Comment by wheelerlaw** [comment]
So. now that I am thinking about this, should this functionality be its own plugin? Instead of making changes to `dnf` itself to support these changes, I could just make another plugin and do a little copy-pasta?

**Comment by xsuchy** [comment]
+1 to this. This will ease the `fedora-upgrade` workflow.

**Comment by kontura** [comment]
> So, now that I am thinking about this, should this functionality be its own plugin? Instead of making changes to dnf itself to support these changes, I could just make another plugin and do a little copy-pasta?

Hello, sorry for the delay, I also think it would fit better into a new plugin. Plus it would be nice if we could avoid extending current `dnf` API at this point (we are focusing on new [dnf5](https://github.com/rpm-software-management/dnf5)).

**Comment by wheelerlaw** [comment]
Ah, makes sense. Will the existing Python plugins work with dnf5?

**Comment by kontura** [comment]
Unfortunately no.
We needed to do bigger API changes that are not compatible.

If you plan to work on this more maybe it would be more future proof to try making the plugin for dnf5. There is a [plan to switch to it in fedora 39](https://fedoraproject.org/wiki/Changes/ReplaceDnfWithDnf5) but it is already available in rawhide (also in our [COPR](https://copr.fedorainfracloud.org/coprs/rpmsoftwaremanagement/dnf5-unstable/) for other fedoras). You might run into things that don't work yet but we would welcome feedback and reports on problems.

We already have couple of plugins for dnf5: https://github.com/rpm-software-management/dnf5/tree/main/dnf5-plugins they are in C++ though, it is possible to also create them in python but I don't think we have that documented yet.

I think it would be nice if we had for example a new command for the `repo` subcommand. It could be used like:
```
dnf5 repo import-gpg-keys
```
Or something like that.

**Comment by kontura** [comment]
I am closing this, as previously discussed we should add a new separate plugin either here or even better find a solution for dnf5.

**Pull request closed without merging**
