### PR TITLE
sourcerpm does not contain epoch (RhBug:1335959)

### PR DESCRIPTION
**Pull request by MichaelMraka**

### CODE REVIEW

**Comment by ignatenkobrain** [comment]
LGTM

**Comment by ignatenkobrain** [comment]
commit e16827fa7676c337104ee4486ad3ebbf4f1b3693
```
Author: Michael Mraka <michael.mraka@redhat.com>
Date:   Wed May 18 10:03:42 2016 +0200

    repoquery: sourcerpm does not contain epoch (RhBug:1335959)
    
    Reference: https://bugzilla.redhat.com/show_bug.cgi?id=1335959
    Signed-off-by: Michael Mraka <michael.mraka@redhat.com>
    Acked-by: Igor Gnatenko <ignatenko@redhat.com>
```

@MichaelMraka please next time add some link into commit and write at least one line of description why this change is needed.

Also, @jsilhan @mluscon @MichaelMraka should we cherry-pick this into dnf-1.1 branch?

**Comment by jsilhan** [comment]
@ignatenkobrain yes, bug fixes shoudl go into fnd-1 branch too - Everything that does not have `dnf-2` label.

**Comment by ignatenkobrain** [comment]
Cherry-picked as f8b657f8312ef3f462d82618e439ec2453be3795

**Pull request closed without merging**
