### PR TITLE
builddep more verbose

### PR DESCRIPTION
**Pull request by jsilhan**

### CODE REVIEW

**Comment by jsilhan** [comment]
changed

**Comment by rholy** [comment]
The other false positives are not needed. I mean the "cli member" and the "unused args". Add DNF to PYTHONPATH and it won't complain (e.g. install DNF or use ```PYTHONPATH=path/to/dnf scripts/lint plugins/builddep.py```).

**Comment by jsilhan** [comment]
changed

**Comment by rholy** [comment]
FTR: one test is failing now

**Comment by jsilhan** [comment]
changed

**Comment by rholy** [comment]
Merged, thanks.

**Comment by ringerc** [comment]
This fixes Bugzilla #1155211

**Pull request merged**
