### PR TITLE
DNF-completion plugin print some info (RhBug:1322562)

### PR DESCRIPTION
**Pull request by stepasm**
Dnf-completion plugin will print info also to stdout when generating cache.

References:https://bugzilla.redhat.com/show_bug.cgi?id=1322562

### CODE REVIEW

**Comment by stepasm** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;esYsPOXW&#x2F;480-stepan-bug-list"> Stepan bug list</a>

**Comment by ignatenkobrain** [comment]
I definitely dont agree for info loglevel as this is debug.

**Comment by stepasm** [comment]
I think that there should be given some feedback to user.

**Comment by ignatenkobrain** [comment]
Not really. It's useless information for user.

**Comment by stepasm** [comment]
If the user needs to wait he should know that something is happening.

**Comment by ignatenkobrain** [comment]
user does not care about such things. For him program is still not finished.

**Comment by ignatenkobrain** [comment]
This should be done in DNF itself.

Before each hook it should print to stdout list of plugins which will be executed and into log when and which plugin was executed.

**Pull request closed without merging**
