### PR TITLE
spec: add a %{snapshot} macro for easier snapshot building

### PR DESCRIPTION
**Pull request by rholy**
See https://github.com/rpm-software-management/hawkey/pull/91

### CODE REVIEW

**Comment by rholy** [comment]
I assume that this can be merged since the same change was OK for hawkey.

**Comment by jsilhan** [comment]
If it was ok then merge the hawkey one too

**Comment by jsilhan** [comment]
actually it's there just PR is open

**Comment by mluscon** [comment]
I am sorry, I forgot to merge this one.

**Pull request merged**
