### PR TITLE
repoquery: add globbing support to whatrequires/whatprovides. (RhBug:1249073)(RhBug:Related:1259650)

### PR DESCRIPTION
**Pull request by megaumi**

### CODE REVIEW

**Comment by jsilhan** [comment]
Jenkins, test this please

**Comment by jsilhan** [comment]
Can you rather erase `by_provides` and `by_requires` methods, please. They no longer needs sack and we can call filter directly - the lines would be even shorter. (There's no API method in plugins, only in `dnfpluginscore/lib.py` with `# :api` comment under method definition)

**Comment by rholy** [comment]
Jenkins, add to whitelist.

**Comment by rholy** [comment]
Jenkins, retest this please. (Actually, I need to test Jenkins, not this ;) )

**Comment by rholy** [comment]
Jenkins, retest this please.

**Comment by jsilhan** [comment]
Really good job with your changes across hawkey, dnf and plugins. Merged, thanks

**Pull request closed without merging**
