### PR TITLE
Reposync: compatibility with yum-utils version (RhBug:1405789)

### PR DESCRIPTION
**Pull request by m-blaha**
https://bugzilla.redhat.com/show_bug.cgi?id=1405789

Added functionality:
* option --newest-only to download only newest packages per repo
* option --delete to delete local packages no longer present in repository
* option --downloadcomps to download comps.xml file for repos
* option --arch for filtering packages by architecture
* option --source to operate on source packages

### CODE REVIEW

**Comment by j-mracek** [comment]
@rh-atomic-bot try

**Comment by j-mracek** [comment]
@rh-atomic-bot try

**Comment by m-blaha** [comment]
@rh-atomic-bot try

**Comment by m-blaha** [comment]
@rh-atomic-bot retry

**Comment by j-mracek** [comment]
The code looks fine

**Comment by j-mracek** [comment]
@rh-atomic-bot r+

**Comment by j-mracek** [comment]
@rh-atomic-bot retry

**Pull request closed without merging**
