### PR TITLE
Change minimal required version

### PR DESCRIPTION
**Pull request by j-mracek**
If from dnf 2.0 downgrade to 1.9 it has to requires downgrade of
dnf-plugins-core. The patch should provides the behavior.

### CODE REVIEW

**Comment by mluscon** [comment]
r+

**Comment by ignatenkobrain** [comment]
@dnf-bot retry

**Comment by ignatenkobrain** [comment]
@dnf-bot retry

**Comment by ignatenkobrain** [comment]
@dnf-bot retry

**Comment by ignatenkobrain** [comment]
@dnf-bot retry

**Comment by ignatenkobrain** [comment]
@dnf-bot retry

**Pull request closed without merging**
