### PR TITLE
dnf repoquery --resolve is extremely slow  (RhBug:1279538)

### PR DESCRIPTION
**Pull request by MichaelMraka**
don't use globs when not necessary
performance improvement
Requires rpm-software-management/dnf#482

### CODE REVIEW

**Comment by keszybz** [comment]
Out of curiosity, what's the performance improvement (e.g. on the https://bugzilla.redhat.com/show_bug.cgi?id=1279538#c21 test case)?

**Comment by MichaelMraka** [comment]
yum repoquery:
time   repoquery -q -C --requires --resolve glibc
...
real	0m3.763s
user	0m0.707s
sys	0m0.410s

dnf repoquery before
time dnf repoquery -q -C --requires --resolve glibc
...
real	8m38.467s
user	8m27.835s
sys	0m7.743s


dnf repoquery fixed
time dnf repoquery -q -C --requires --resolve glibc
...
real	0m3.179s
user	0m2.634s
sys	0m0.497s

**Comment by keszybz** [comment]
Thanks. That's impressive.

**Comment by mluscon** [comment]
retest this please

**Comment by MichaelMraka** [comment]
Merged efdcde08e62597b507eb7b4d00e07e364dd65b5e.

**Pull request closed without merging**
