### PR TITLE
[reposync] Fix --delete with multiple repos (RhBug:1774103)

### PR DESCRIPTION
**Pull request by m-blaha**
When reposync was used with --delete option and multiple repositories
to sync, only packages from the latest repository were kept and all
downloaded content from former repositories was imediately deleted.

Additionaly it fixes the problem with multiple packages having the same
filename (in different subdirectories) in one repository. In this case
when --delete option was used, only one of those files was kept and the
others were deleted.

https://bugzilla.redhat.com/show_bug.cgi?id=1774103

Test: https://github.com/rpm-software-management/ci-dnf-stack/pull/713

### CODE REVIEW

**Comment by Conan-Kudo** [comment]
@rh-atomic-bot r+

**Comment by m-blaha** [comment]
@rh-atomic-bot retry

**Comment by m-blaha** [comment]
@rh-atomic-bot retry

**Comment by m-blaha** [comment]
@rh-atomic-bot retry

**Comment by m-blaha** [comment]
I disabled the failing test scenario, it's unrelated to this PR.

**Pull request merged**
