### PR TITLE
debuginfo-install: accept packages names specified as NEVRA (RhBug:1171046)

### PR DESCRIPTION
**Pull request by spacekpe**

### CODE REVIEW

**Comment by rholy** [comment]
We agreed that writing tests against plugins might be more work that writing the plugins itself. However, it isn't impossible. So if you don't have time to write them, fix at least the other comments, please.

**Comment by spacekpe** [comment]
Okay, I replaced returnPkgLists with get_best_query instead. I hope this was the last point (except missing unit tests).

IMHO bigger changes like version selection algorithm should be made in separate commits.

**Comment by mluscon** [comment]
No issues spotted during functionality testing.

**Comment by jsilhan** [comment]
Merged, thanks

**Pull request closed without merging**
