### PR TITLE
Conditionalize building of python2 subpackages

### PR DESCRIPTION
**Pull request by m-blaha**

### CODE REVIEW

**Comment by torsava** [comment]
The conditionalization looks good to me!
One thing though, you're dropping the python2 subpackages for Fedora > 28, but one of the subpackages (python2-dnf-plugins-core) is not a leaf and stuff depend on it. Therefore I don't think it can be dropped from Fedora just yet.

**Comment by stratakis** [comment]
A nice graphical [representation](http://fedora.portingdb.xyz/pkg/dnf-plugins-core/) of which packages are leaves in Fedora.

**Comment by stratakis** [comment]
Is it possible to move this forward?

**Comment by j-mracek** [comment]
@ignatenkobrain How do you think it will be possible to check users of python2 plugins?

**Comment by j-mracek** [comment]
@rh-atomic-bot try

**Comment by j-mracek** [comment]
The code looks fine.

**Comment by j-mracek** [comment]
@rh-atomic-bot r+

**Pull request closed without merging**
