### PR TITLE
[copr] allow utf-8 user input (RhBug:1244125)

### PR DESCRIPTION
**Pull request by FrostyX**
Hello,
this PR fixes [1244125](https://bugzilla.redhat.com/show_bug.cgi?id=1244125).

Can you please review it @evilkost ?

### CODE REVIEW

**Comment by ignatenkobrain** [comment]
LGTM

**Comment by xsuchy** [comment]
I tested it and it works and it solve the mentioned BZ.

**Comment by xsuchy** [comment]
I merged the code, but I have no ACL to close this PR (and github do not do that automatically). Can somebody close this PR or grant me necessary permission?

**Comment by jsilhan** [comment]
I see it closed, You have the write access so  you can close PRs, etc.

**Comment by FrostyX** [comment]
Yeah, we saw it wrong, sorry. There is no `[closed]` label, only `[merged]`, so we thought that it is still open. But you are right, this PR is no longer listed in opened ones, so I guess we are done here. :sunglasses:

**Pull request merged**
