### PR TITLE
DNF2: make plugin command registration easier

### PR DESCRIPTION
**Pull request by MichaelMraka**
Depends on rpm-software-management/dnf#478.
Replaces plugin class to register command with simple decorator.

### CODE REVIEW

**Comment by xsuchy** [comment]
You will need to change dnf_lowest_compatible in spec file too. But yeah, you can get the number only when the PR in dnf itself is merged.

**Comment by mluscon** [comment]
Please fix:

Traceback (most recent call last):
  File "/home/mluscon/projects/dnf/dnf/plugin.py", line 124, in import_modules
    module = importlib.import_module(name)
  File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/lib/python2.7/site-packages/dnf-plugins/download.py", line 37, in <module>
    class DownloadCommand(dnf.cli.Command):
  File "/home/mluscon/projects/dnf/dnf/plugin.py", line 147, in register_command
    "name": command_class.aliases[0]})

**Comment by MichaelMraka** [comment]
@mluscon fixed (in dnf/master)

**Comment by mluscon** [comment]
ok, merged

**Pull request closed without merging**
